---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haibolv.
--- DateTime: 2026/8/7
---

-- 原子回滚秒杀库存与用户下单记录
-- 用于 Kafka 发送失败时的补偿操作，保证库存不丢失

-- 1.参数列表
-- 1.1 优惠券 ID
local voucherId = ARGV[1]
-- 1.2 用户 ID
local userId = ARGV[2]

-- 2. 数据Key
-- 2.1 库存key
local stockKey = "seckill:stock:" .. voucherId
-- 2.2 订单key
local orderKey = "seckill:order:" .. voucherId

-- 3. 原子回滚
-- 3.1 恢复库存 incrby stockKey 1
redis.call("incrby", stockKey, 1)
-- 3.2 移除用户下单记录，允许用户重新抢购
redis.call("srem", orderKey, userId)
return 0
