---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haibolv.
--- DateTime: 2026/6/14 22:22
---

-- 利用redis中的集合（set）在lua脚本中来实现秒杀资格判断
-- 注意：订单落库已解耦至 Kafka，Lua 只负责原子性的资格校验与库存扣减

-- 1.参数列表
-- 1.1 优惠券 ID
local voucherId = ARGV[1]
-- 1.2 用户 ID
local userId = ARGV[2]

-- 2. 数据Key
-- 2.1 库存key
local stockKey = "seckill:stock:" .. voucherId
-- 2.2 订单key
local orderKey = "seckill:order:" .. voucherId

-- 3. 脚本逻辑
-- 3.1 判断库存是否充足 get stockKey
-- redis中是字符串，所以需要tonumber转换成数字
if (tonumber(redis.call("get", stockKey)) <= 0) then
    return 1
end
-- 3.2 判断用户是否重复下单 sismember orderKey userId
if(redis.call("sismember", orderKey,userId) == 1) then
    -- 用户存在，说明是重复下单
    return 2
end
-- 3.3 扣减库存 incrby stockKey -1
redis.call("incrby", stockKey, -1)
-- 3.4 记录用户已经下单 sadd orderKey userId
redis.call("sadd", orderKey, userId)
-- 3.5 订单落库由 Kafka 消费者异步处理，此处不再写入 Redis Stream
return 0